export const postsData = [
    {
      id: 1,
      image: "https://devby.io/storage/images/30/54/62/03/derived/48b77668b36d851798a8708487b3148e.jpg",
      text: "«Лаборатория Касперского» проанализировала 193 миллиона паролей, которые были обнаружены в даркнете. 45% из них (87 миллионов) злоумышленники могут подобрать менее чем за минуту.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Хакеры могут подобрать почти половину паролей в даркнете за минуту",
      author: 4,
      favorite: false,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 2,
      image: "https://devby.io/storage/images/20/82/94/58/derived/f5ff71e5d843bebb9bb3f80a9074d66b.jpg",
      text: "Европарламент рассматривает законопроект, согласно которому в ЕС будет разрешено массово сканировать переписку в мессенджерах. Документ предусматривает внедрение системы «модерации загрузки». Она предполагает сканирование всех отправляемых человеком сообщений, включая изображения, видео и ссылки.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "В ЕС хотят сканировать любую переписку, даже зашифрованную",
      author: 5,
      favorite: true,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 3,
      image: "https://devby.io/storage/images/89/53/75/48/derived/f801a9349f3bd0d3df542bf4048dcf13.jpg",
      text: "Я проживаю в Польше. Не так давно поменял права на польские: я это обязан сделать по закону, а ещё у старых беларусских истекал срок действия. И вот на днях из каршерингового сервиса Anytime в Беларуси мне пришло уведомление, что я должен предоставить новые права (что логично).",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Беларус поменял права на польские. В каршеринге на родине его ждал сюрприз",
      author: 3,
      favorite: false,
      popular: false,
      like: false,
      dislike: false,
    },
    {
      id: 4,
      image: "https://devby.io/storage/images/23/79/73/69/derived/8817caddce0cc685ffcb54361fdf7efa.jpg",
      text: "Учёба в вузе стоит много времени и денег, поэтому желающих попасть в ИТ-сферу очень интересует, имеет ли смысл тратиться на «корочку».",
      date: "2021-12-12",
      lesson_num: 1,
      title: "В каких ИТ-профессиях реже всего требуют диплом?",
      author: 4,
      favorite: false,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 5,
      image: "https://devby.io/storage/images/52/22/65/98/derived/bff6bd85b6392eb1e784b25b46d5f7bb.jpg",
      text: "«Билет на игру подарили друзья» Известный беларусский айтишник Миша Ларченко приехал в Германию из Нидерландов и уже побывал в фан-зонах в Мюнхене и Франкфурте. 22 июня вживую посмотрел игру Португалия-Турция на стадионе в Дортмунде.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "«Атмосферу портят немецкие законы». Айтишники на Евро-2024 — во сколько обошлось и что удивило",
      author: 5,
      favorite: true,
      popular: false,
      like: false,
      dislike: false,
    },
    {
      id: 6,
      image: "https://devby.io/storage/images/19/85/93/68/derived/e81232bcceb80e678ca172ed6ebbb54c.jpg",
      text: "Запускаем в Adviser «Карьерную Википедию», где будем собирать гайды от состоявшихся специалистов. Первый выпуск, конечно же, про Machine Learning — самую главную сферу IT в 2024 году. Сегодня наш собеседник — Анна, Lead Machine Learning Engineer. Выбрали для разговора с ней 8 самых важных вопросов о карьере в ML: как сделать карьерный свитч в желанную сферу, что для этого нужно прокачать, как проходить собесы, что читать, учить, смотреть и как дальше развиваться в профессии.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "8 вопросов специалисту про карьеру в ML: все про стек, собесы, рост в профессии и как туда свитчнуться",
      author: 3,
      favorite: false,
      popular: false,
      like: false,
      dislike: false,
    },
    {
      id: 7,
      image: "https://devby.io/storage/images/45/30/16/80/derived/a0c5ca43b67545f49be4714370c32e7e.jpg",
      text: "Shadow Team Lead — одна из загадочных позиций, типичных для аутсорса. Этот тайтл регулярно всплывает в нашем цикле про то, как дела у аутсорс-компаний. Как айтишникам работается в тени?",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Shadow Lead и другие. Чем айтишники занимаются в тени",
      author: 4,
      favorite: true,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 8,
      image: "https://devby.io/storage/images/32/09/50/26/derived/b9d1ab536602d7f12fbc11ed56ea04f1.jpg",
      text: "Хакер под ником IntelBroker, который известен взлломом крупных компаний и ведомств, теперь заявил, что смог похитить внутреннюю документацию Apple. Сообщение появилось на одном из хакерских форумов в даркнете, пишет 9to5Mac.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Хакеры взломали Apple, украли код внутренних инструментов",
      author: 5,
      favorite: true,
      popular: false,
      like: false,
      dislike: false,
    },
    {
      id: 9,
      image: "https://devby.io/storage/images/25/56/29/14/derived/8b78d1bd07d056f0a87d37113b0e81a3.jpg",
      text: "Платформа отменила Premium-подписки нескольких пользователей, которые купили более дешевые варианты с помощью технологии VPN.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Youtube отменяет дешевые подписки, купленные с помощью VPN",
      author: 3,
      favorite: false,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 10,
      image: "https://devby.io/storage/images/33/17/56/93/derived/e5ff4b47a6e37e26a5f7bf81de69138e.jpg",
      text: "Компания показала новую языковую модель Claude 3.5 Sonnet. По словам разработчиков, он может сравниться и в чем-то превосходит по возможностям GPT-4o от OpenAI и Gemini от Google.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Anthropic выпустила Claude 3.5 Sonnet — ИИ-модель опережает GPT-4o и Gemini",
      author: 5,
      favorite: true,
      popular: true,
      like: false,
      dislike: false,
    },
    {
      id: 11,
      image: "https://devby.io/storage/images/11/16/36/87/derived/fb1ca27a55483575e049b9336509dbf3.jpg",
      text: "В феврале Dell ввела RTO-политику и потребовала от сотрудников определиться: работать по гибридному графику или удалённо. Первые должны ходить в офис 39 дней в квартал, а для трекинга посещаемости придумана специальная цветовая система. Предпочитающие второе не смогут рассчитывать на повышение и менять позиции внутри компании.",
      date: "2021-12-12",
      lesson_num: 1,
      title: "Dell: «Никаких повышений для удалёнщиков». Половина сотрудников: «ОK»",
      author: 3,
      favorite: false,
      popular: false,
      like: false,
      dislike: false,
    },
  ];